name: Ruby

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: "Test"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: Test
      run: bundle exec ruby test/alert_in_ua2_twitter_test.rb
